config/routes.rb
Rails.application.routes.draw do
  root 'home#show'

  get '/cinema', to: 'home#cinema'
  get '/showings', to: 'home#showings'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cinema.rb
class Cinema
  attr_reader :name, :address, :id

  def initialize(data)
    @name = data['name']
    @address = data['address']
    @id = data['venue_id']
  end
end

app/models/film.rb
class Film
  attr_reader :title, :times

  def initialize(data)
    @title = data['title']
    @times = data['time']
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  end

  def cinema
    lookup = CinemaService::Lookup.new(params[:postcode])
    @cinema = lookup.closest
  end

  def showings
    showings = CinemaService::Showings.new(params[:cinema_id])
    @films = showings.get
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/cinema.js.erb
$('#cinema .name').text('<%= @cinema.name %>')
$('#cinema .address').text('<%= @cinema.address %>')
$('#cinema .link').html('<%= link_to "Get Films!", showings_path(cinema_id: @cinema.id), remote: true %>')
$('#cinema .times').empty()
$('#cinema').show()

app/views/home/show.html.slim
= form_tag cinema_path, method: :get, remote: true do
  p Enter a postcode!
  = text_field_tag :postcode, 'RG2 9FB'
  = submit_tag 'Find nearest cinema!'

#cinema
  h3 Your nearest cinema
  h1.name
  h2.address

  .link
  .times

app/views/home/showings.js.erb
$('#cinema .times').empty()
<% @films.each do |film| %>
  $('#cinema .times').append('<h4><%= film.title %></h4><p><%= film.times.join(", ") %></p>')
<% end %>
$('#cinema .link').empty()

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FilmFinder</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>